# Generated by Django 5.2.13 on 2026-04-26 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_room_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/gallery/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='Подпись')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Фото номера',
                'verbose_name_plural': 'Фотографии номеров',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
