# Generated by Django 5.2 on 2026-06-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fix_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='YooKassa ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('caretaker', 'Специалист по уходу'), ('client', 'Клиент')], default='client', max_length=20, verbose_name='Роль'),
        ),
    ]
