# Generated by Django 5.2 on 2026-06-04 13:09

from django.db import migrations, models
from django.utils import timezone


def backfill_period_and_titles(apps, schema_editor):
    """Проставить период по плановому времени и согласовать типовые названия."""
    Task = apps.get_model('core', 'Task')

    def period_for_hour(hour):
        if 5 <= hour < 12:
            return 'morning'
        if 12 <= hour < 17:
            return 'day'
        if 17 <= hour < 22:
            return 'evening'
        return 'night'

    adjectives = {
        'morning': ('Утренний', 'Утренняя', 'Утреннее'),
        'day': ('Дневной', 'Дневная', 'Дневное'),
        'evening': ('Вечерний', 'Вечерняя', 'Вечернее'),
        'night': ('Ночной', 'Ночная', 'Ночное'),
    }
    # ключевое слово -> (базовое название, индекс рода: 0=м, 1=ж, 2=ср)
    syncable = {
        'кормление': ('кормление', 2),
        'прогулка': ('прогулка', 1),
        'уборка': ('уборка вольера', 1),
        'осмотр': ('осмотр', 0),
    }

    for task in Task.objects.all():
        if not task.scheduled_time:
            continue
        period = period_for_hour(timezone.localtime(task.scheduled_time).hour)
        new_title = task.title
        low = task.title.lower()
        for keyword, (base, gender_index) in syncable.items():
            if keyword in low:
                new_title = f'{adjectives[period][gender_index]} {base}'
                break
        Task.objects.filter(pk=task.pk).update(period=period, title=new_title)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_yookassa_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='period',
            field=models.CharField(blank=True, choices=[('morning', 'Утро'), ('day', 'День'), ('evening', 'Вечер'), ('night', 'Ночь')], max_length=10, verbose_name='Период суток'),
        ),
        migrations.RunPython(backfill_period_and_titles, noop_reverse),
    ]
