# Generated by Django 5.2 on 2026-06-04 18:44

from django.db import migrations, models


REMOVE_NAMES = ['Стандартное кормление', 'Выгул (30 мин)', 'Дополнительный уход']
DAILY_NAMES  = ['Дополнительный выгул']


def update_services(apps, schema_editor):
    Service = apps.get_model('core', 'Service')
    Service.objects.filter(name__in=REMOVE_NAMES).update(status='inactive')
    Service.objects.filter(name__in=DAILY_NAMES).update(is_daily=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_task_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_daily',
            field=models.BooleanField(default=False, verbose_name='Начисляется за каждую ночь'),
        ),
        migrations.RunPython(update_services, noop),
    ]
